kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-nas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas
---
kind: Pod
apiVersion: v1
metadata:
  name: pvpod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: persistent-volume-claim-nas
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
